### ISSUE TITLE
Don't use bind in render()

### ISSUE THREAD

**Issue by braco** [MichaelCereda/react-native-form-generator#45]
Hey Michael

Got some warnings about "x events ahead of JS - try to make your JS faster" when using an InputField (with maxLength, not sure if that matters) and looked a little deeper at your code.

You shouldn't use this.func.bind(this) in render, as it creates a new function on every render. This might be the problem, as there are quite a few function binds in lib/*.js

You can bind in the constructor, or bind to the component instance with:
```
   boundFunction = () => {

  }
```
which makes this.boundFunction available in render without bind.

You might want to consider eslint with the react plugins, it's a lifesaver for me:
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

See also
http://reactkungfu.com/2015/07/why-and-how-to-bind-methods-in-your-react-component-classes/
https://medium.com/@esamatti/react-js-pure-render-performance-anti-pattern-fb88c101332f#.1l6dw4m4k

**Comment by MichaelCereda** [comment]
Yes you're right..
I changed inputComponent and I'm going to change all the other components.

I'm almosto 99% sure it was me, I was there that day.

**Comment by LAITONEN** [comment]
**# My working solution to this problem:**
**What I had before:** Values of the Inputs were this.props, onChangeText called a function which sent the input to the action creator, which then dispatched it to the Reducer which returned the input text as a certain prop of the input page (this.prop.certainProp). And, as you already guessed, this was happening on every input change (one sign added/removed - onChangeText fires) making the whole program very cumbersome.
**What solved the issue:** instead of constantly accessing the action creator, I simply started to update the state (by creating the required values on top of the component as follows:
state = { value1: '', value2:'', value3:'' } and so forth.
The values of the inputs, which before were the this.props, are now the state properties(this.state.value1 instead of this.props.value1 that I was getting by updates from the reducer through mapStateToProps). After I typed everything I needed in the designated inputs, I am now sending the values of the state to the createObject action creator:
this.props.createObject({ this.state.value1, this.state.value2 etc}).
And this object adds the values to the database. 
**Conclusion:** Swifter, more efficient and pleasant to use apPayPal
